spring:
  application:
    name: blurlink
  datasource:
    url: jdbc:mysql://localhost:3306/blurlink?useSSL=true
    username: root
    password: 'test123'
  jpa:
    open-in-view: false

server:
  port: 8080